spring.application.name=forms
spring.config.import=classpath:keys/google_api_key.properties
spring.jackson.property-naming-strategy=SNAKE_CASE
#spring.profiles.active=dev
telegram.authorized.user.id=0
google.oauth.token.dir=/app/data/tokens